version: '3'

services:
  cloud-storage:
    image: buuhvprojects/cloud-storage:1.6.0
    container_name: cloud-storage
    restart: on-failure
    volumes:
      - ./:/app:rw
    env_file: .env
    environment:
      - PORT=$PORT
      - DEV_MODE=${DEV_MODE}
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
    ports:
      - "$PORT:$PORT"
  db-mysql:
    image: mysql:5.6
    restart: always
    env_file: .env
    container_name: cloud-storage_db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASS}
    ports:
      - "${MYSQL_EXTERNAL_PORT}:${MYSQL_INTERNAL_PORT}"
    volumes:
      - ./db-sql/buuhv_cloud_storage/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db-sql/mysql-structure:/var/lib/mysql
      - ./db-sql/my.cnf:/etc/mysql/my.cnf